spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        maxIdle: 100
        minIdle: 0
        maxActive: 300
        maxWait: 10000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
